name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Download config
      run: |
        $configPath = "$env:USERPROFILE\Desktop\openvpn.ovpn"
        Invoke-WebRequest -Uri https://cc.golexor.com/vnc.ovpn -OutFile $configPath
      shell: powershell

    - name: Install OpenVPN
      run: choco install -y openvpn --package-parameters="/InstallDir=C:\Tools\OpenVPN /AddToDesktop /Gui /GuiOnLogon /EasyRsa /DcoDriver /TapDriver /WintunDriver /OpenSSL"
     

    - name: Create Tunnel
      run: |
        dir C:\Tools\OpenVPN
        $openVpnPath = "$env:C:\Tools\OpenVPN\bin\OpenVPN.exe"
        $configPath = "$env:USERPROFILE\Desktop\openvpn.ovpn"
        Start-Process -FilePath $openVpnPath -ArgumentList "--config $configPath" -Verb RunAs
      shell: powershell
      
